# Generated by Django 4.2.24 on 2025-09-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0003_location_remove_person_location_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="death_datetime",
        ),
    ]
