# Generated by Django 4.2.24 on 2025-09-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0004_remove_death_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="language_skill_level",
        ),
        migrations.RemoveField(
            model_name="patientinfo",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="person",
            name="language_skill_level",
        ),
        migrations.RemoveField(
            model_name="person",
            name="primary_language_concept",
        ),
        migrations.CreateModel(
            name="PersonLanguageSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("speak", "Speak"),
                            ("write", "Write"),
                            ("both", "Both Speak and Write"),
                        ],
                        help_text="Language skill level: speak, write, both",
                        max_length=10,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the person's primary language?",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "language_concept",
                    models.ForeignKey(
                        db_column="language_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_language_skills",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_skills",
                        to="omop_core.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_language_skill",
                "indexes": [
                    models.Index(
                        fields=["person", "is_primary"],
                        name="person_lang_person__ec6431_idx",
                    )
                ],
                "unique_together": {("person", "language_concept")},
            },
        ),
    ]
