# Generated by Django 4.2.24 on 2025-09-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0005_add_person_language_skills"),
    ]

    operations = []
