# Generated by Django 4.2.24 on 2025-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0006_remove_cancer_fields_from_condition_occurrence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="behavior_concept",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="clinical_stage_group",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="grade_concept",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="histology_concept",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="laterality",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="metastatic_sites",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="pathologic_stage_group",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="primary_site_concept",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="progression_status",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="staging_system",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tnm_clinical_m",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tnm_clinical_n",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tnm_clinical_t",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tnm_pathologic_m",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tnm_pathologic_n",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tnm_pathologic_t",
        ),
        migrations.RemoveField(
            model_name="conditionoccurrence",
            name="tumor_size_cm",
        ),
    ]
