# Generated by Django 4.2.24 on 2025-09-16 16:01

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove VitalSignMeasurement model to improve OMOP CDM compliance.
    
    Vital signs should be stored in the standard OMOP Measurement table
    using standardized LOINC concepts instead of a custom model.
    """

    dependencies = [
        ("omop_core", "0007_remove_cancer_fields_from_condition_occurrence"),
    ]

    operations = [
        migrations.DeleteModel(
            name='VitalSignMeasurement',
        ),
    ]
