# Generated by Django 4.2.24 on 2025-09-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0008_remove_vitalsignmeasurement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MeasurementExtension",
        ),
    ]
