# Generated by Django 4.2.24 on 2025-09-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0009_remove_measurement_extension"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ObservationExtension",
        ),
    ]
