# Generated by Django 4.2.24 on 2025-09-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0010_delete_observationextension"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="qualifier_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="qualifier_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="measurement_qualifiers",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="value_as_string",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
