# Generated by Django 4.2.24 on 2025-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0011_measurement_qualifier_concept_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="qualifier_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
