# Generated by Django 4.2.24 on 2026-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0012_measurement_qualifier_source_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personlanguageskill",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("speak", "Speak/Understand"),
                    ("write", "Write/Read"),
                    ("both", "Both Speak and Write"),
                ],
                help_text="Language skill level: speak, write, both",
                max_length=10,
            ),
        ),
    ]
