# Generated by Django 5.2.6 on 2026-01-20 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0013_alter_personlanguageskill_skill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="personlanguageskill",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("speak", "Speak"),
                    ("write", "Write"),
                    ("both", "Both Speak and Write"),
                ],
                help_text="Language skill level: speak, write, both",
                max_length=10,
            ),
        ),
    ]
