# Generated by Django 5.2.6 on 2026-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0014_patientinfo_created_at_patientinfo_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
