# Generated by Django 5.2.6 on 2026-01-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0015_patientinfo_date_of_birth_patientinfo_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="birth_datetime",
        ),
        migrations.RemoveField(
            model_name="person",
            name="care_site_id",
        ),
        migrations.RemoveField(
            model_name="person",
            name="day_of_birth",
        ),
        migrations.RemoveField(
            model_name="person",
            name="ethnicity_source_concept",
        ),
        migrations.RemoveField(
            model_name="person",
            name="ethnicity_source_value",
        ),
        migrations.RemoveField(
            model_name="person",
            name="gender_source_concept",
        ),
        migrations.RemoveField(
            model_name="person",
            name="gender_source_value",
        ),
        migrations.RemoveField(
            model_name="person",
            name="location",
        ),
        migrations.RemoveField(
            model_name="person",
            name="month_of_birth",
        ),
        migrations.RemoveField(
            model_name="person",
            name="person_source_value",
        ),
        migrations.RemoveField(
            model_name="person",
            name="provider_id",
        ),
        migrations.RemoveField(
            model_name="person",
            name="race_source_concept",
        ),
        migrations.RemoveField(
            model_name="person",
            name="race_source_value",
        ),
        migrations.AlterField(
            model_name="person",
            name="ethnicity_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="ethnicity_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_ethnicity",
                to="omop_core.concept",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="gender_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_gender",
                to="omop_core.concept",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="person",
            name="race_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="race_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_race",
                to="omop_core.concept",
            ),
        ),
    ]
