# Generated by Django 4.2.16 on 2026-01-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0017_alter_person_gender_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="phone_number",
        ),
    ]
