# Generated by Django 4.2.16 on 2026-01-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0018_remove_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="race_concept",
        ),
        migrations.RemoveField(
            model_name="person",
            name="year_of_birth",
        ),
    ]
