# Generated by Django 4.2.16 on 2026-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0019_remove_person_race_concept_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="day_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="month_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="year_of_birth",
            field=models.IntegerField(default=1970),
            preserve_default=False,
        ),
    ]
