# Generated by Django 4.2.16 on 2026-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0020_person_day_of_birth_person_month_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
