# Generated by Django 4.2.16 on 2026-01-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0021_patientinfo_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="care_site_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="ethnicity_source_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="ethnicity_source_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_ethnicity_source",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="ethnicity_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gender_source_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="gender_source_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_gender_source",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="gender_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="location_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="provider_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="race_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="race_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_race",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="race_source_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="race_source_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_race_source",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="race_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="year_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
