# Generated by Django 4.2.16 on 2026-01-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0021_make_person_fields_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="care_site_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="day_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="death_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="ethnicity_source_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="ethnicity_source_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_ethnicity_source",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="ethnicity_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gender_source_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="gender_source_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_gender_source",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="gender_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="language_skill_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="location_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="month_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="person_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="primary_language_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_language_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_primary_language",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="provider_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="race_source_concept",
            field=models.ForeignKey(
                blank=True,
                db_column="race_source_concept_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_race_source",
                to="omop_core.concept",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="race_source_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="secondary_languages",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="year_of_birth",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
