# Generated by Django 4.2.16 on 2026-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0022_update_person_omop_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="lymph_node_status",
            field=models.CharField(
                blank=True,
                help_text="Lymph node status (Positive/Negative/Unknown)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="metastasis_status",
            field=models.CharField(
                blank=True,
                help_text="Metastasis status (Positive/Negative/Unknown)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="tumor_size",
            field=models.FloatField(
                blank=True, help_text="Tumor size in cm", null=True
            ),
        ),
    ]
