# Generated by Django 4.2.16 on 2026-01-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0023_add_tumor_characteristics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureOccurrence",
            fields=[
                (
                    "procedure_occurrence_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("procedure_date", models.DateField()),
                ("procedure_datetime", models.DateTimeField(blank=True, null=True)),
                ("procedure_end_date", models.DateField(blank=True, null=True)),
                ("procedure_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("provider_id", models.IntegerField(blank=True, null=True)),
                ("visit_detail_id", models.IntegerField(blank=True, null=True)),
                (
                    "procedure_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "modifier_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "modifier_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="modifier_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_modifiers",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
                (
                    "procedure_concept",
                    models.ForeignKey(
                        db_column="procedure_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_occurrences",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "procedure_source_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="procedure_source_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_sources",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "procedure_type_concept",
                    models.ForeignKey(
                        db_column="procedure_type_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_types",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "visit_occurrence",
                    models.ForeignKey(
                        blank=True,
                        db_column="visit_occurrence_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.visitoccurrence",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_occurrence",
            },
        ),
    ]
