# Generated by Django 4.2.16 on 2026-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0024_procedureoccurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="family_name",
            field=models.CharField(
                blank=True, help_text="Last/Family name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="given_name",
            field=models.CharField(
                blank=True, help_text="First/Given name", max_length=100, null=True
            ),
        ),
    ]
