# Generated by Django 4.2.16 on 2026-01-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0025_person_family_name_person_given_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='albumin_g_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Albumin (g/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='alc_thousand_per_ul',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Absolute Lymphocyte Count (10³/µL)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='alkaline_phosphatase_u_l',
            field=models.IntegerField(blank=True, help_text='Alkaline Phosphatase (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='alt_u_l',
            field=models.IntegerField(blank=True, help_text='ALT (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='amc_thousand_per_ul',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Absolute Monocyte Count (10³/µL)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='anc_thousand_per_ul',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Absolute Neutrophil Count (10³/µL)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ast_u_l',
            field=models.IntegerField(blank=True, help_text='AST (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='bilirubin_total_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total Bilirubin (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='bnp_pg_ml',
            field=models.IntegerField(blank=True, help_text='BNP (pg/mL)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='bun_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Blood Urea Nitrogen (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ca19_9_u_ml',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='CA 19-9 (U/mL)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='calcium_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calcium (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='cea_ng_ml',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='CEA (ng/mL)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='creatinine_clearance_ml_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Creatinine Clearance (mL/min)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='creatinine_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Creatinine (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='egfr_ml_min_173m2',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='eGFR (mL/min/1.73m²)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='glucose_mg_dl',
            field=models.IntegerField(blank=True, help_text='Glucose (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='hba1c_percent',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='HbA1c (%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='hematocrit_percent',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hematocrit (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='hemoglobin_g_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hemoglobin (g/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='INR', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ldh_u_l',
            field=models.IntegerField(blank=True, help_text='LDH (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='magnesium_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Magnesium (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='platelet_count_thousand_per_ul',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Platelet Count (10³/µL)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='potassium_meq_l',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Potassium (mEq/L)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='psa_ng_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PSA (ng/mL)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='pt_seconds',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='PT (seconds)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ptt_seconds',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='PTT (seconds)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='rbc_million_per_ul',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Red Blood Cell Count (10⁶/µL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='serum_calcium_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Serum Calcium (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='serum_creatinine_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum Creatinine (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='sodium_meq_l',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Sodium (mEq/L)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='troponin_ng_ml',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Troponin (ng/mL)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='wbc_count_thousand_per_ul',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='White Blood Cell Count (10³/µL)', max_digits=6, null=True),
        ),
    ]
