# Generated by Django 4.2.16 on 2026-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0026_patientinfo_albumin_g_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='beta2_microglobulin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Beta-2 Microglobulin (mg/L)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='blood_urea_nitrogen',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Blood Urea Nitrogen (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='c_reactive_protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='C-Reactive Protein (mg/L)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='egfr',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='eGFR (mL/min/1.73m²)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='esr',
            field=models.IntegerField(blank=True, help_text='ESR (mm/hr)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ldh_level',
            field=models.IntegerField(blank=True, help_text='LDH (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='serum_potassium',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Serum Potassium (mEq/L)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='serum_sodium',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Serum Sodium (mEq/L)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='total_protein',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total Protein (g/dL)', max_digits=5, null=True),
        ),
    ]
