# Generated by Django 5.2.7 on 2026-03-10 08:28
# Fixed: use IF NOT EXISTS so the migration is idempotent when columns
# were already added by a previous (non-Django) schema change.

from django.db import migrations, models


ADD_SQL = """
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS absolute_lymphocyte_count DOUBLE PRECISION;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS alkaline_phosphatase INTEGER;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS androgen_receptor_status VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS autoimmune_cytopenias_refractory_to_steroids BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS bcl2_inhibitor_refractory BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS binet_stage TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS bone_marrow_involvement BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS btk_inhibitor_refractory BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS clonal_b_lymphocyte_count INTEGER;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS clonal_bone_marrow_b_lymphocytes DOUBLE PRECISION;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS disease_activity TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS ecog_assessment_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS first_line_discontinuation_reason VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS first_line_end_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS first_line_intent VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS first_line_start_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS flipi_score INTEGER;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS flipi_score_options TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS gelf_criteria_status TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS hepatomegaly BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS ki67_percentage NUMERIC(5, 1);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS languages_skills TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS largest_lymph_node_size DOUBLE PRECISION;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS later_discontinuation_reason VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS later_end_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS later_intent VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS later_start_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS later_therapies JSONB DEFAULT '[]'::jsonb;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS ldh INTEGER;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS lymphadenopathy BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS lymphocyte_doubling_time INTEGER;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS magnesium NUMERIC(5, 1);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS measurable_disease_imwg BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS measurable_disease_iwcll BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS oncotype_dx_score INTEGER;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS phosphorus NUMERIC(5, 1);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS pregnancy_test_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS pregnancy_test_result_value VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS protein_expressions TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS qtcf_value DOUBLE PRECISION;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS reason_for_discontinuation VARCHAR(100);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS report_interpretation VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS richter_transformation TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS second_line_discontinuation_reason VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS second_line_end_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS second_line_intent VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS second_line_start_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS serum_beta2_microglobulin_level DOUBLE PRECISION;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS spleen_size DOUBLE PRECISION;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS splenomegaly BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS status TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS supportive_therapy_end_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS supportive_therapy_intent VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS supportive_therapy_start_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS test_date DATE;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS test_methodology VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS test_specimen_type VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS therapy_intent VARCHAR(50);
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS tp53_disruption BOOLEAN;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS tumor_burden TEXT;
    ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS tumor_grade INTEGER;
"""

DROP_SQL = """
    ALTER TABLE patient_info DROP COLUMN IF EXISTS tumor_grade;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS tumor_burden;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS tp53_disruption;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS therapy_intent;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS test_specimen_type;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS test_methodology;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS test_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS supportive_therapy_start_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS supportive_therapy_intent;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS supportive_therapy_end_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS status;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS splenomegaly;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS spleen_size;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS serum_beta2_microglobulin_level;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS second_line_start_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS second_line_intent;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS second_line_end_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS second_line_discontinuation_reason;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS richter_transformation;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS report_interpretation;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS reason_for_discontinuation;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS qtcf_value;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS protein_expressions;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS pregnancy_test_result_value;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS pregnancy_test_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS phosphorus;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS oncotype_dx_score;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS measurable_disease_iwcll;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS measurable_disease_imwg;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS magnesium;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS lymphocyte_doubling_time;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS lymphadenopathy;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS ldh;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS later_therapies;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS later_start_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS later_intent;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS later_end_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS later_discontinuation_reason;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS largest_lymph_node_size;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS languages_skills;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS ki67_percentage;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS hepatomegaly;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS gelf_criteria_status;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS flipi_score_options;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS flipi_score;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS first_line_start_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS first_line_intent;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS first_line_end_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS first_line_discontinuation_reason;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS ecog_assessment_date;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS disease_activity;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS clonal_bone_marrow_b_lymphocytes;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS clonal_b_lymphocyte_count;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS btk_inhibitor_refractory;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS bone_marrow_involvement;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS binet_stage;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS bcl2_inhibitor_refractory;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS autoimmune_cytopenias_refractory_to_steroids;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS androgen_receptor_status;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS alkaline_phosphatase;
    ALTER TABLE patient_info DROP COLUMN IF EXISTS absolute_lymphocyte_count;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0035_add_planned_therapies'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=ADD_SQL, reverse_sql=DROP_SQL),
            ],
            state_operations=[
                migrations.AddField(model_name='patientinfo', name='absolute_lymphocyte_count', field=models.FloatField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='alkaline_phosphatase', field=models.IntegerField(blank=True, help_text='Alkaline Phosphatase (U/L)', null=True)),
                migrations.AddField(model_name='patientinfo', name='androgen_receptor_status', field=models.CharField(blank=True, help_text='Androgen Receptor Status', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='autoimmune_cytopenias_refractory_to_steroids', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='bcl2_inhibitor_refractory', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='binet_stage', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='bone_marrow_involvement', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='btk_inhibitor_refractory', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='clonal_b_lymphocyte_count', field=models.IntegerField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='clonal_bone_marrow_b_lymphocytes', field=models.FloatField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='disease_activity', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='ecog_assessment_date', field=models.DateField(blank=True, help_text='ECOG Performance Status Assessment Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='first_line_discontinuation_reason', field=models.CharField(blank=True, help_text='First Line Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='first_line_end_date', field=models.DateField(blank=True, help_text='First Line Therapy End Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='first_line_intent', field=models.CharField(blank=True, help_text='First Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='first_line_start_date', field=models.DateField(blank=True, help_text='First Line Therapy Start Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='flipi_score', field=models.IntegerField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='flipi_score_options', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='gelf_criteria_status', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='hepatomegaly', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='ki67_percentage', field=models.DecimalField(blank=True, decimal_places=1, help_text='Ki-67 Percentage', max_digits=5, null=True)),
                migrations.AddField(model_name='patientinfo', name='languages_skills', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='largest_lymph_node_size', field=models.FloatField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='later_discontinuation_reason', field=models.CharField(blank=True, help_text='Later Line Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='later_end_date', field=models.DateField(blank=True, help_text='Later Line Therapy End Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='later_intent', field=models.CharField(blank=True, help_text='Later Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='later_start_date', field=models.DateField(blank=True, help_text='Later Line Therapy Start Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='later_therapies', field=models.JSONField(blank=True, default=list)),
                migrations.AddField(model_name='patientinfo', name='ldh', field=models.IntegerField(blank=True, help_text='LDH (U/L)', null=True)),
                migrations.AddField(model_name='patientinfo', name='lymphadenopathy', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='lymphocyte_doubling_time', field=models.IntegerField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='magnesium', field=models.DecimalField(blank=True, decimal_places=1, help_text='Magnesium (mg/dL)', max_digits=5, null=True)),
                migrations.AddField(model_name='patientinfo', name='measurable_disease_imwg', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='measurable_disease_iwcll', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='oncotype_dx_score', field=models.IntegerField(blank=True, help_text='Oncotype DX Score', null=True)),
                migrations.AddField(model_name='patientinfo', name='phosphorus', field=models.DecimalField(blank=True, decimal_places=1, help_text='Phosphorus (mg/dL)', max_digits=5, null=True)),
                migrations.AddField(model_name='patientinfo', name='pregnancy_test_date', field=models.DateField(blank=True, help_text='Pregnancy Test Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='pregnancy_test_result_value', field=models.CharField(blank=True, help_text='Pregnancy Test Result (Positive/Negative)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='protein_expressions', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='qtcf_value', field=models.FloatField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='reason_for_discontinuation', field=models.CharField(blank=True, help_text='Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=100, null=True)),
                migrations.AddField(model_name='patientinfo', name='report_interpretation', field=models.CharField(blank=True, help_text='Report Interpretation (Positive/Negative/Indeterminate/Not Tested)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='richter_transformation', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='second_line_discontinuation_reason', field=models.CharField(blank=True, help_text='Second Line Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='second_line_end_date', field=models.DateField(blank=True, help_text='Second Line Therapy End Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='second_line_intent', field=models.CharField(blank=True, help_text='Second Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='second_line_start_date', field=models.DateField(blank=True, help_text='Second Line Therapy Start Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='serum_beta2_microglobulin_level', field=models.FloatField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='spleen_size', field=models.FloatField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='splenomegaly', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='status', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='supportive_therapy_end_date', field=models.DateField(blank=True, help_text='Supportive Therapy End Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='supportive_therapy_intent', field=models.CharField(blank=True, help_text='Supportive Therapy Intent', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='supportive_therapy_start_date', field=models.DateField(blank=True, help_text='Supportive Therapy Start Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='test_date', field=models.DateField(blank=True, help_text='Test Date', null=True)),
                migrations.AddField(model_name='patientinfo', name='test_methodology', field=models.CharField(blank=True, help_text='Test Methodology (NGS/IHC/FISH/PCR)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='test_specimen_type', field=models.CharField(blank=True, help_text='Test Specimen Type (Primary/Metastatic Biopsy)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='therapy_intent', field=models.CharField(blank=True, help_text='Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True)),
                migrations.AddField(model_name='patientinfo', name='tp53_disruption', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='tumor_burden', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='patientinfo', name='tumor_grade', field=models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
