# Generated by Django 5.2.6 on 2026-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0035_add_planned_therapies"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="ai_lines_of_therapy",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated lines of therapy from HealthTree (core__ai_lines_of_therapy). Array of LOT objects, one per treatment line, ordered by line_number.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="alkaline_phosphatase",
            field=models.IntegerField(
                blank=True, help_text="Alkaline Phosphatase (U/L)", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="androgen_receptor_status",
            field=models.CharField(
                blank=True,
                help_text="Androgen Receptor Status",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="ecog_assessment_date",
            field=models.DateField(
                blank=True,
                help_text="ECOG Performance Status Assessment Date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="first_line_discontinuation_reason",
            field=models.CharField(
                blank=True,
                help_text="First Line Reason for Discontinuation (Progression/Toxicity/Completion)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="first_line_end_date",
            field=models.DateField(
                blank=True, help_text="First Line Therapy End Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="first_line_intent",
            field=models.CharField(
                blank=True,
                help_text="First Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="first_line_start_date",
            field=models.DateField(
                blank=True, help_text="First Line Therapy Start Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="ki67_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Ki-67 Percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="later_discontinuation_reason",
            field=models.CharField(
                blank=True,
                help_text="Later Line Reason for Discontinuation (Progression/Toxicity/Completion)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="later_end_date",
            field=models.DateField(
                blank=True, help_text="Later Line Therapy End Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="later_intent",
            field=models.CharField(
                blank=True,
                help_text="Later Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="later_start_date",
            field=models.DateField(
                blank=True, help_text="Later Line Therapy Start Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="ldh",
            field=models.IntegerField(blank=True, help_text="LDH (U/L)", null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="magnesium",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Magnesium (mg/dL)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="oncotype_dx_score",
            field=models.IntegerField(
                blank=True, help_text="Oncotype DX Score", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="phosphorus",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Phosphorus (mg/dL)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="pregnancy_test_date",
            field=models.DateField(
                blank=True, help_text="Pregnancy Test Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="pregnancy_test_result_value",
            field=models.CharField(
                blank=True,
                help_text="Pregnancy Test Result (Positive/Negative)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="reason_for_discontinuation",
            field=models.CharField(
                blank=True,
                help_text="Reason for Discontinuation (Progression/Toxicity/Completion)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="report_interpretation",
            field=models.CharField(
                blank=True,
                help_text="Report Interpretation (Positive/Negative/Indeterminate/Not Tested)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="second_line_discontinuation_reason",
            field=models.CharField(
                blank=True,
                help_text="Second Line Reason for Discontinuation (Progression/Toxicity/Completion)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="second_line_end_date",
            field=models.DateField(
                blank=True, help_text="Second Line Therapy End Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="second_line_intent",
            field=models.CharField(
                blank=True,
                help_text="Second Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="second_line_start_date",
            field=models.DateField(
                blank=True, help_text="Second Line Therapy Start Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="supportive_therapy_end_date",
            field=models.DateField(
                blank=True, help_text="Supportive Therapy End Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="supportive_therapy_intent",
            field=models.CharField(
                blank=True,
                help_text="Supportive Therapy Intent",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="supportive_therapy_start_date",
            field=models.DateField(
                blank=True, help_text="Supportive Therapy Start Date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="survey_responses",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Patient survey responses from HealthTree (core__survey_responses). Array of response objects, one per user/survey/question combination.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="test_date",
            field=models.DateField(blank=True, help_text="Test Date", null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="test_methodology",
            field=models.CharField(
                blank=True,
                help_text="Test Methodology (NGS/IHC/FISH/PCR)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="test_specimen_type",
            field=models.CharField(
                blank=True,
                help_text="Test Specimen Type (Primary/Metastatic Biopsy)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="therapy_intent",
            field=models.CharField(
                blank=True,
                help_text="Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)",
                max_length=50,
                null=True,
            ),
        ),
    ]
