# Generated by Django 5.2.7 on 2026-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0035_add_planned_therapies'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='absolute_lymphocyte_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='alkaline_phosphatase',
            field=models.IntegerField(blank=True, help_text='Alkaline Phosphatase (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='androgen_receptor_status',
            field=models.CharField(blank=True, help_text='Androgen Receptor Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='autoimmune_cytopenias_refractory_to_steroids',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='bcl2_inhibitor_refractory',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='binet_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='bone_marrow_involvement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='btk_inhibitor_refractory',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='clonal_b_lymphocyte_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='clonal_bone_marrow_b_lymphocytes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='disease_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ecog_assessment_date',
            field=models.DateField(blank=True, help_text='ECOG Performance Status Assessment Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='first_line_discontinuation_reason',
            field=models.CharField(blank=True, help_text='First Line Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='first_line_end_date',
            field=models.DateField(blank=True, help_text='First Line Therapy End Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='first_line_intent',
            field=models.CharField(blank=True, help_text='First Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='first_line_start_date',
            field=models.DateField(blank=True, help_text='First Line Therapy Start Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='flipi_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='flipi_score_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='gelf_criteria_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='hepatomegaly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ki67_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ki-67 Percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='languages_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='largest_lymph_node_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='later_discontinuation_reason',
            field=models.CharField(blank=True, help_text='Later Line Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='later_end_date',
            field=models.DateField(blank=True, help_text='Later Line Therapy End Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='later_intent',
            field=models.CharField(blank=True, help_text='Later Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='later_start_date',
            field=models.DateField(blank=True, help_text='Later Line Therapy Start Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='later_therapies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ldh',
            field=models.IntegerField(blank=True, help_text='LDH (U/L)', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='lymphadenopathy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='lymphocyte_doubling_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='magnesium',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Magnesium (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='measurable_disease_imwg',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='measurable_disease_iwcll',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='oncotype_dx_score',
            field=models.IntegerField(blank=True, help_text='Oncotype DX Score', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='phosphorus',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Phosphorus (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='pregnancy_test_date',
            field=models.DateField(blank=True, help_text='Pregnancy Test Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='pregnancy_test_result_value',
            field=models.CharField(blank=True, help_text='Pregnancy Test Result (Positive/Negative)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='protein_expressions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='qtcf_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='reason_for_discontinuation',
            field=models.CharField(blank=True, help_text='Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='report_interpretation',
            field=models.CharField(blank=True, help_text='Report Interpretation (Positive/Negative/Indeterminate/Not Tested)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='richter_transformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='second_line_discontinuation_reason',
            field=models.CharField(blank=True, help_text='Second Line Reason for Discontinuation (Progression/Toxicity/Completion)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='second_line_end_date',
            field=models.DateField(blank=True, help_text='Second Line Therapy End Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='second_line_intent',
            field=models.CharField(blank=True, help_text='Second Line Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='second_line_start_date',
            field=models.DateField(blank=True, help_text='Second Line Therapy Start Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='serum_beta2_microglobulin_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='spleen_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='splenomegaly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='supportive_therapy_end_date',
            field=models.DateField(blank=True, help_text='Supportive Therapy End Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='supportive_therapy_intent',
            field=models.CharField(blank=True, help_text='Supportive Therapy Intent', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='supportive_therapy_start_date',
            field=models.DateField(blank=True, help_text='Supportive Therapy Start Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='test_date',
            field=models.DateField(blank=True, help_text='Test Date', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='test_methodology',
            field=models.CharField(blank=True, help_text='Test Methodology (NGS/IHC/FISH/PCR)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='test_specimen_type',
            field=models.CharField(blank=True, help_text='Test Specimen Type (Primary/Metastatic Biopsy)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='therapy_intent',
            field=models.CharField(blank=True, help_text='Therapy Intent (Adjuvant/Neoadjuvant/Metastatic)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='tp53_disruption',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='tumor_burden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='tumor_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
