# Generated by Django 5.2.6 on 2026-03-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0036_add_cll_and_missing_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="ki67_percentage",
        ),
    ]
