# Generated by Django 5.2.6 on 2026-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0037_remove_ht_lot_and_survey_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="ki67_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Ki-67 Percentage",
                max_digits=5,
                null=True,
            ),
        ),
    ]
