# Generated by Django 5.2.6 on 2026-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0038_add_ki67_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="ki67_percentage",
        ),
    ]
