# Generated by Django 5.2.6 on 2025-09-16 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('omop_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerModifier',
            fields=[
                ('cancer_modifier_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cancer_modifier_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cancer_modifier_concept', models.ForeignKey(db_column='cancer_modifier_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='cancer_modifiers', to='omop_core.concept')),
                ('cancer_modifier_source_concept', models.ForeignKey(blank=True, db_column='cancer_modifier_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancer_modifier_sources', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
            ],
            options={
                'db_table': 'cancer_modifier',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('episode_start_date', models.DateField()),
                ('episode_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('episode_end_date', models.DateField(blank=True, null=True)),
                ('episode_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('episode_parent_id', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('episode_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('episode_concept', models.ForeignKey(db_column='episode_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='omop_core.concept')),
                ('episode_object_concept', models.ForeignKey(db_column='episode_object_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='episode_objects', to='omop_core.concept')),
                ('episode_source_concept', models.ForeignKey(blank=True, db_column='episode_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='episode_sources', to='omop_core.concept')),
                ('episode_type_concept', models.ForeignKey(db_column='episode_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='episode_types', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='Histology',
            fields=[
                ('histology_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('histology_date', models.DateField()),
                ('histology_datetime', models.DateTimeField(blank=True, null=True)),
                ('episode_id', models.BigIntegerField(blank=True, null=True)),
                ('histology_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('modifier_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('concept', models.ForeignKey(db_column='concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='histology_concepts', to='omop_core.concept')),
                ('histology_source_concept', models.ForeignKey(blank=True, db_column='histology_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histology_source_concepts', to='omop_core.concept')),
                ('histology_type_concept', models.ForeignKey(db_column='histology_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='histology_types', to='omop_core.concept')),
                ('lateral_concept', models.ForeignKey(blank=True, db_column='lateral_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histology_laterals', to='omop_core.concept')),
                ('modifier_concept', models.ForeignKey(blank=True, db_column='modifier_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histology_modifiers', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
                ('primary_site_concept', models.ForeignKey(blank=True, db_column='primary_site_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histology_primary_sites', to='omop_core.concept')),
                ('visit_occurrence', models.ForeignKey(blank=True, db_column='visit_occurrence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.visitoccurrence')),
            ],
            options={
                'db_table': 'histology',
            },
        ),
        migrations.CreateModel(
            name='StemTable',
            fields=[
                ('domain_id', models.CharField(max_length=20)),
                ('visit_detail_id', models.IntegerField(blank=True, null=True)),
                ('provider_id', models.IntegerField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('verbatim_end_date', models.DateField(blank=True, null=True)),
                ('days_supply', models.IntegerField(blank=True, null=True)),
                ('dose_unit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('modifier_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_high', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('range_low', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('refills', models.IntegerField(blank=True, null=True)),
                ('route_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('sig', models.TextField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('unique_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('value_as_number', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('value_as_string', models.CharField(blank=True, max_length=60, null=True)),
                ('value_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('anatomic_site_concept', models.ForeignKey(blank=True, db_column='anatomic_site_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_anatomic_site_concepts', to='omop_core.concept')),
                ('concept', models.ForeignKey(db_column='concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='stem_concepts', to='omop_core.concept')),
                ('disease_status_concept', models.ForeignKey(blank=True, db_column='disease_status_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_disease_status_concepts', to='omop_core.concept')),
                ('modifier_concept', models.ForeignKey(blank=True, db_column='modifier_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_modifier_concepts', to='omop_core.concept')),
                ('operator_concept', models.ForeignKey(blank=True, db_column='operator_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_operator_concepts', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
                ('route_concept', models.ForeignKey(blank=True, db_column='route_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_route_concepts', to='omop_core.concept')),
                ('source_concept', models.ForeignKey(blank=True, db_column='source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_source_concepts', to='omop_core.concept')),
                ('specimen_source', models.ForeignKey(blank=True, db_column='specimen_source_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_specimen_source_concepts', to='omop_core.concept')),
                ('tumor_grade_concept', models.ForeignKey(blank=True, db_column='tumor_grade_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_tumor_grade_concepts', to='omop_core.concept')),
                ('tumor_stage_concept', models.ForeignKey(blank=True, db_column='tumor_stage_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_tumor_stage_concepts', to='omop_core.concept')),
                ('type_concept', models.ForeignKey(db_column='type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='stem_type_concepts', to='omop_core.concept')),
                ('unit_concept', models.ForeignKey(blank=True, db_column='unit_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_unit_concepts', to='omop_core.concept')),
                ('value_as_concept', models.ForeignKey(blank=True, db_column='value_as_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stem_value_concepts', to='omop_core.concept')),
                ('visit_occurrence', models.ForeignKey(blank=True, db_column='visit_occurrence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.visitoccurrence')),
            ],
            options={
                'db_table': 'stem_table',
            },
        ),
        migrations.CreateModel(
            name='EpisodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.BigIntegerField()),
                ('event_id', models.BigIntegerField()),
                ('episode_event_field_concept', models.ForeignKey(db_column='episode_event_field_concept_id', on_delete=django.db.models.deletion.PROTECT, to='omop_core.concept')),
            ],
            options={
                'db_table': 'episode_event',
                'unique_together': {('episode_id', 'event_id', 'episode_event_field_concept')},
            },
        ),
    ]
