# Generated by Django 4.2.24 on 2025-09-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "omop_oncology",
            "0002_socialdeterminant_infectionstatus_healthbehavior_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infectionstatus",
            name="infection_concept",
        ),
        migrations.RemoveField(
            model_name="infectionstatus",
            name="person",
        ),
        migrations.RemoveField(
            model_name="socialdeterminant",
            name="determinant_concept",
        ),
        migrations.RemoveField(
            model_name="socialdeterminant",
            name="person",
        ),
        migrations.RemoveField(
            model_name="socialdeterminant",
            name="value_as_concept",
        ),
        migrations.AlterUniqueTogether(
            name="treatmentline",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="treatmentline",
            name="person",
        ),
        migrations.DeleteModel(
            name="HealthBehavior",
        ),
        migrations.DeleteModel(
            name="InfectionStatus",
        ),
        migrations.DeleteModel(
            name="SocialDeterminant",
        ),
        migrations.DeleteModel(
            name="TreatmentLine",
        ),
    ]
