# Generated by Django 5.2.6 on 2025-09-16 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('omop_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicVariantOccurrence',
            fields=[
                ('genomic_variant_occurrence_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('genomic_variant_occurrence_datetime', models.DateTimeField()),
                ('structural_variant_end_position', models.BigIntegerField(blank=True, null=True)),
                ('structural_variant_start_position', models.BigIntegerField(blank=True, null=True)),
                ('variant_occurrence_id_in_haplotype', models.BigIntegerField(blank=True, null=True)),
                ('reference_allele', models.TextField(blank=True, null=True)),
                ('alternative_allele', models.TextField(blank=True, null=True)),
                ('read_depth', models.IntegerField(blank=True, null=True)),
                ('allelic_frequency', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('information_source', models.CharField(blank=True, max_length=100, null=True)),
                ('genomic_variant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('chromosome_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('genomic_source_class_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('zygosity_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('phase_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('genomic_variant_start_position', models.BigIntegerField(blank=True, null=True)),
                ('genomic_variant_end_position', models.BigIntegerField(blank=True, null=True)),
                ('variant_type_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('chromosome_concept', models.ForeignKey(blank=True, db_column='chromosome_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chromosomes', to='omop_core.concept')),
                ('chromosome_source_concept', models.ForeignKey(blank=True, db_column='chromosome_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chromosome_sources', to='omop_core.concept')),
                ('gene_concept', models.ForeignKey(blank=True, db_column='gene_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genes', to='omop_core.concept')),
                ('gene_source_concept', models.ForeignKey(blank=True, db_column='gene_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gene_sources', to='omop_core.concept')),
                ('genomic_source_class_concept', models.ForeignKey(blank=True, db_column='genomic_source_class_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_source_classes', to='omop_core.concept')),
                ('genomic_source_class_source_concept', models.ForeignKey(blank=True, db_column='genomic_source_class_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_source_class_sources', to='omop_core.concept')),
                ('genomic_variant_concept', models.ForeignKey(db_column='genomic_variant_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='genomic_variants', to='omop_core.concept')),
                ('genomic_variant_source_concept', models.ForeignKey(blank=True, db_column='genomic_variant_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_variant_sources', to='omop_core.concept')),
                ('genomic_variant_type_concept', models.ForeignKey(db_column='genomic_variant_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='genomic_variant_types', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
                ('phase_concept', models.ForeignKey(blank=True, db_column='phase_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phase_concepts', to='omop_core.concept')),
                ('phase_source_concept', models.ForeignKey(blank=True, db_column='phase_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phase_sources', to='omop_core.concept')),
                ('variant_type_concept', models.ForeignKey(blank=True, db_column='variant_type_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_types', to='omop_core.concept')),
                ('variant_type_source_concept', models.ForeignKey(blank=True, db_column='variant_type_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_type_sources', to='omop_core.concept')),
                ('visit_occurrence', models.ForeignKey(blank=True, db_column='visit_occurrence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.visitoccurrence')),
                ('zygosity_concept', models.ForeignKey(blank=True, db_column='zygosity_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zygosity_concepts', to='omop_core.concept')),
                ('zygosity_source_concept', models.ForeignKey(blank=True, db_column='zygosity_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zygosity_sources', to='omop_core.concept')),
            ],
            options={
                'db_table': 'genomic_variant_occurrence',
            },
        ),
        migrations.CreateModel(
            name='GenomicVariantAnnotation',
            fields=[
                ('genomic_variant_annotation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('annotation_datetime', models.DateTimeField()),
                ('annotation_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('annotation_text', models.TextField(blank=True, null=True)),
                ('annotation_numeric_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('annotation_unit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('annotation_concept', models.ForeignKey(db_column='annotation_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='omop_core.concept')),
                ('annotation_source_concept', models.ForeignKey(blank=True, db_column='annotation_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_sources', to='omop_core.concept')),
                ('annotation_type_concept', models.ForeignKey(db_column='annotation_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='annotation_types', to='omop_core.concept')),
                ('annotation_unit_concept', models.ForeignKey(blank=True, db_column='annotation_unit_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_units', to='omop_core.concept')),
                ('annotation_unit_source_concept', models.ForeignKey(blank=True, db_column='annotation_unit_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_unit_sources', to='omop_core.concept')),
                ('genomic_variant_occurrence', models.ForeignKey(db_column='genomic_variant_occurrence_id', on_delete=django.db.models.deletion.CASCADE, to='omop_genomics.genomicvariantoccurrence')),
            ],
            options={
                'db_table': 'genomic_variant_annotation',
            },
        ),
        migrations.CreateModel(
            name='GenomicTestResult',
            fields=[
                ('genomic_test_result_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('genomic_test_datetime', models.DateTimeField()),
                ('genomic_test_result_numeric_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('genomic_test_result_text_value', models.TextField(blank=True, null=True)),
                ('genomic_test_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('genomic_test_result_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('genomic_test_unit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('genomic_test_concept', models.ForeignKey(db_column='genomic_test_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='genomic_tests', to='omop_core.concept')),
                ('genomic_test_result_concept', models.ForeignKey(blank=True, db_column='genomic_test_result_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_test_results', to='omop_core.concept')),
                ('genomic_test_result_source_concept', models.ForeignKey(blank=True, db_column='genomic_test_result_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_test_result_sources', to='omop_core.concept')),
                ('genomic_test_source_concept', models.ForeignKey(blank=True, db_column='genomic_test_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_test_sources', to='omop_core.concept')),
                ('genomic_test_unit_concept', models.ForeignKey(blank=True, db_column='genomic_test_unit_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_test_units', to='omop_core.concept')),
                ('genomic_test_unit_source_concept', models.ForeignKey(blank=True, db_column='genomic_test_unit_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomic_test_unit_sources', to='omop_core.concept')),
                ('measurement', models.ForeignKey(blank=True, db_column='measurement_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='omop_core.measurement')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
                ('visit_occurrence', models.ForeignKey(blank=True, db_column='visit_occurrence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.visitoccurrence')),
                ('genomic_variant_occurrence', models.ForeignKey(blank=True, db_column='genomic_variant_occurrence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='omop_genomics.genomicvariantoccurrence')),
            ],
            options={
                'db_table': 'genomic_test_result',
            },
        ),
        migrations.CreateModel(
            name='MolecularSequence',
            fields=[
                ('molecular_sequence_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sequence_datetime', models.DateTimeField()),
                ('sequence_assembly_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence_start_position', models.BigIntegerField(blank=True, null=True)),
                ('sequence_end_position', models.BigIntegerField(blank=True, null=True)),
                ('sequence_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence_type_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('genomic_variant_occurrence', models.ForeignKey(blank=True, db_column='genomic_variant_occurrence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='omop_genomics.genomicvariantoccurrence')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
                ('sequence_assembly_concept', models.ForeignKey(blank=True, db_column='sequence_assembly_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_assemblies', to='omop_core.concept')),
                ('sequence_assembly_source_concept', models.ForeignKey(blank=True, db_column='sequence_assembly_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_assembly_sources', to='omop_core.concept')),
                ('sequence_source_concept', models.ForeignKey(blank=True, db_column='sequence_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_sources', to='omop_core.concept')),
                ('sequence_type_concept', models.ForeignKey(db_column='sequence_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='sequence_types', to='omop_core.concept')),
                ('sequence_type_source_concept', models.ForeignKey(blank=True, db_column='sequence_type_source_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_type_sources', to='omop_core.concept')),
                ('visit_occurrence', models.ForeignKey(blank=True, db_column='visit_occurrence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.visitoccurrence')),
            ],
            options={
                'db_table': 'molecular_sequence',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('specimen_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('specimen_date', models.DateField()),
                ('specimen_datetime', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specimen_source_id', models.CharField(blank=True, max_length=50, null=True)),
                ('specimen_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('anatomic_site_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('disease_status_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('anatomic_site_concept', models.ForeignKey(blank=True, db_column='anatomic_site_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimen_anatomic_sites', to='omop_core.concept')),
                ('disease_status_concept', models.ForeignKey(blank=True, db_column='disease_status_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimen_disease_status', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
                ('specimen_concept', models.ForeignKey(db_column='specimen_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='omop_core.concept')),
                ('specimen_type_concept', models.ForeignKey(db_column='specimen_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='specimen_types', to='omop_core.concept')),
                ('unit_concept', models.ForeignKey(blank=True, db_column='unit_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimen_units', to='omop_core.concept')),
            ],
            options={
                'db_table': 'specimen',
            },
        ),
    ]
