# Generated by Django 4.2.24 on 2025-09-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0003_location_remove_person_location_id_and_more"),
        ("omop_genomics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TumorAssessment",
            fields=[
                (
                    "tumor_assessment_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("assessment_date", models.DateField()),
                ("assessment_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment_method",
                    models.CharField(
                        choices=[
                            ("RECIST_1_1", "RECIST 1.1"),
                            ("RANO", "RANO"),
                            ("IMWG", "IMWG"),
                            ("CLINICAL", "Clinical Assessment"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Assessment methodology",
                        max_length=50,
                    ),
                ),
                (
                    "overall_response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CR", "Complete Response"),
                            ("PR", "Partial Response"),
                            ("SD", "Stable Disease"),
                            ("PD", "Progressive Disease"),
                            ("NE", "Not Evaluable"),
                            ("MR", "Minimal Response"),
                            ("VGPR", "Very Good Partial Response"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_lesions_sum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of target lesions (mm)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("new_lesions_present", models.BooleanField(blank=True, null=True)),
                (
                    "non_target_lesion_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "disease_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEASURABLE", "Measurable Disease"),
                            ("NON_MEASURABLE", "Non-measurable Disease"),
                            ("NO_EVIDENCE", "No Evidence of Disease"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
            ],
            options={
                "db_table": "tumor_assessment",
            },
        ),
        migrations.CreateModel(
            name="BiomarkerMeasurement",
            fields=[
                (
                    "biomarker_measurement_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("measurement_date", models.DateField()),
                ("measurement_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "value_as_number",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "value_as_string",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "biomarker_type",
                    models.CharField(
                        choices=[
                            ("HORMONE_RECEPTOR", "Hormone Receptor"),
                            ("HER2", "HER2/neu"),
                            ("PD_L1", "PD-L1"),
                            ("PROLIFERATION", "Proliferation Marker"),
                            ("GENETIC", "Genetic Marker"),
                            ("OTHER", "Other Biomarker"),
                        ],
                        help_text="Type of biomarker",
                        max_length=50,
                    ),
                ),
                (
                    "assay_method",
                    models.CharField(
                        blank=True,
                        help_text="Assay method used",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(
                        blank=True,
                        help_text="Testing laboratory",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        blank=True, help_text="Specimen type", max_length=50, null=True
                    ),
                ),
                (
                    "clinical_significance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                            ("EQUIVOCAL", "Equivocal"),
                            ("UNKNOWN", "Unknown"),
                            ("HIGH", "High"),
                            ("LOW", "Low"),
                            ("INTERMEDIATE", "Intermediate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "biomarker_concept",
                    models.ForeignKey(
                        db_column="biomarker_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biomarker_measurements",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
                (
                    "unit_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biomarker_units",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "value_as_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="value_as_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biomarker_values",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "biomarker_measurement",
            },
        ),
    ]
