# Generated by Django 4.2.24 on 2026-01-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("omop_core", "0013_alter_personlanguageskill_skill_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_user",
                        to="omop_core.person",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patient_user",
            },
        ),
        migrations.CreateModel(
            name="PatientMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sender_is_patient", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="patient_portal.patientuser",
                    ),
                ),
            ],
            options={
                "db_table": "patient_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("data_sharing", "Data Sharing"),
                            ("clinical_trial", "Clinical Trial Participation"),
                            ("research", "Research Use"),
                        ],
                        max_length=50,
                    ),
                ),
                ("consent_granted", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(auto_now_add=True)),
                ("consent_document", models.TextField(blank=True, null=True)),
                (
                    "patient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patient_portal.patientuser",
                    ),
                ),
            ],
            options={
                "db_table": "patient_consent",
                "unique_together": {("patient_user", "consent_type")},
            },
        ),
    ]
