# Generated by Django 4.2.24 on 2026-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmessage",
            name="read_at",
        ),
        migrations.AddField(
            model_name="patientmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
